<?php
/**
 * Message translations.
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    /* 共用 */
    'Admin Manage'                                               => '后台管理',
    'System Home'                                                => '系统首页',
    'Success'                                                    => '成功',
    'Failed'                                                     => '失败',
    'Enable'                                                     => '启用',
    'Disable'                                                    => '禁用',
    'Home Url'                                                   => '前台首页',
    'Update Password'                                            => '修改密码',
    'Login'                                                      => '登录',
    'Logout'                                                     => '退出登录',
    'Incorrect username or password'                             => '错误的用户名或密码',
    'Save'                                                       => '保存',
    'Create'                                                     => '创建',
    'Update'                                                     => '更新',
    'Delete'                                                     => '删除',

    /* 用户 */
    'Users' => '用户管理',
    'Create User' => '创建用户',
    'Update User' => '更新用户',

    /* 设置 */
    'Web Set'                                                    => '站点设置',
    'Web Name'                                                   => '网站名称',
    'Web URL'                                                    => '网站 URL',
    'Web Status'                                                 => '站点开关/关闭说明',
    'Admin Email'                                                => '管理员邮箱',
    'Web ICP Number'                                             => '网站备案号',
    'Please Input ICP Number'                                    => '请填写 ICP 备案号',
    'CopyRight'                                                  => '版权信息',
    'Statistical Code'                                           => '统计代码',
    'Please Input Statistical Code'                              => '请填写第三方统计的 js 代码',
    'User Encrypt Method'                                        => '用户加密方式(一旦更改，原密码将失效)',
    'Support The Crypt Encryption'                               => '支持crypt加密，我们推荐使用它。',
    'Don`t Support The Crypt Encryption'                         => '不支持crypt加密，请选择MD5。',
    'Safe String'                                                => '网站安全密匙',
    'SEO Set'                                                    => 'SEO设置',
    'Upload Set'                                                 => '上传设置',
    'Template Set'                                               => '模板设置',
    'Email Set'                                                  => '邮件设置',
    'Cache Set'                                                  => '缓存设置',
    'Cache Status'                                               => '缓存状态',
    'Cache Type'                                                 => '缓存类型',
    'FileCache'                                                  => '文件缓存',
    'MemCache'                                                   => 'Memcache缓存',
    'RedisCache'                                                 => 'Redis缓存',
    'Please Select'                                              => '==请选择==',
    'IF Enable'                                                  => '是否可用',
    'Cache Enable'                                               => '<font color="green">缓存可用</font>',
    'Cache Disable'                                              => '<font color="red">缓存不可用</font>',
    'Cache Error Msg'                                            => '请检查{cache}环境和相关配置。错误信息：{msg}',
    'CacheFiles Depth'                                           => '缓存目录深度',
    'Cache Host'                                                 => '缓存主机(IP)',
    'Cache Port'                                                 => '缓存端口号',
    'Cache Database'                                             => '缓存数据库名',
    'Only Number'                                                => '仅为数字',
    'Access Set'                                                 => '访问控制设置',
    'Deny Register IP'                                           => '禁止注册ip',
    'Deny Register IP Desc'                                      => '<br/>每个ip地址占一行，ip段用*号表示。<br/>为空表示全部允许, 若全部禁止请填写*.*.*.*',
    'Deny Access IP'                                             => '禁止访问站点ip',
    'Email Active Status'                                        => '激活邮件(包括注册激活，修改邮箱激活)',
    'Email Host'                                                 => '邮箱服务器',
    'Email Port'                                                 => '邮箱端口号',
    'Email FromName'                                             => '邮件发送人姓名',
    'Email UserName'                                             => '邮箱用户名',
    'Email Password'                                             => '邮箱密码',
    'Email TimeOut'                                              => '邮件发送超时时间(单位：秒)',
    'Email ToTest'                                               => '测试收件人邮箱',
    'Test Email'                                                 => '测试邮件',
    'Test Email Desc'                                            => '提交后再进行测试',
    'Send Success'                                               => '发送成功！',
    'Send Failed'                                                => '发送失败，请检查相关配置',
    'Custom Set'                                                 => '自定义设置',
    'More Than Env Limit'                                        => '超过系统限制{size}',
    'WaterMark Alpha Should Between 1 AND 100'                   => '水印透明度应该介于1~100的数字',
    'Test Email Subject'                                         => '测试邮件标题',
    'Test Email Content'                                         => '测试邮件内容',
    'Web Title'                                                  => '网站标题',
    'Web Keywords'                                               => '网站关键字',
    'Web Description'                                            => '网站描述',
    'SEO Title'                                                  => 'SEO 标题',
    'SEO Keywords'                                               => 'SEO 关键字',
    'SEO Description'                                            => 'SEO 描述',
    'App Set'                                                    => 'APP相关参数',
    'welfare_second_title'                                       => '次级福利标题',
    'welfare_second_url'                                         => '次级福利链接',

    /* 栏目 */

    /* 广告 */
    'Ad Manage'                                                  => '广告管理',
    'Ad Title'                                                   => '广告名称',
    'Link Url'                                                   => '链接地址',
    'Image Url'                                                  => '图片地址',
    'Please fill in the full path to the outsite resources'      => '非本站资源请填写完整路径，带http://',
    'Width'                                                      => '宽',
    'Height'                                                     => '高',
    'Ad Intro'                                                   => '广告说明',
    'Image'                                                      => '图片',
    'Auth Init'                                                  => '初始化授权体系',
    'Auth Init Table'                                            => '初始化RBAC表',
    'Auth Manage'                                                => '授权管理',
    'Init Table Will Delete All Auth Data! Are You Sure?'        => '初始化RBAC表，将删除所有授权数据！您确定要进行吗?',
    'Init Auth Will Create New Auth Data! Are You Sure?'         => '初始化授权体系，将重新创建数据并分配角色！您确定要进行吗?',
    'Failed Get'                                                 => '获取失败',
    'Success Get'                                                => '获取成功',
    'Open'                                                       => '开启',
    'Close'                                                      => '关闭',
    'Seconds'                                                    => '秒',
    'Forbidden to upload'                                        => '禁止上传',
    'Menu Manage'                                                => '导航管理',
    'AdPosition'                                                 => '广告位',
    'Adposition Manage'                                          => '广告位管理',
    'AdPosition Name'                                            => '广告位名称',

    /* 软件管理 */

    /* 缓存管理 */
    'Update Cache Success'                                       => '更新缓存成功',
    'Install Test Data'                                          => '安装测试数据',

    //用户
    'You Can Not Delete Yourself'                                => '您不能删除自己',
    'You Can Not Change Yourself'                                => '您不能禁用自己',
    'You Can Not Delete Admin'                                   => '您不能删除超级管理员',
    'You Can Not Change Your Group'                              => '您不能修改自己的权限',
    'You Can Not Change The User Group'                          => '您不能修改该用户的权限',
);
